### ISSUE TITLE
Not creating graph index

### ISSUE THREAD

**Issue by rcalef** [biointec/jabba#6]
Hi,

 I'm having trouble getting jabba to run on my datasets. I followed the guide in the manual: using karat to error-correct my Illumina shotgun reads, brownie to create a corrected de Bruijn graph, and am now trying to run jabba.

I'm getting an error that jabba is unable to load an index for the graph fasta file. It looks like it tries to make the index but no file is created. Here's the command I'm using:

>#! /bin/bash
>
>/usr/bin/time -v jabba \
>  -k 75 \
>  -t 32 \
>  -o output \
>  -g /mnt/projects/correct/analysis/pacbio_ec/jabba/brownie/brownie_output/DBGraph.fasta \
>  -fastq /mnt/projects/correct/data/pacbio/all_reads.fastq \
>  2>&1 | tee run.log

which gives me the following output:

>FileType is fastq.
>Max Number of Threads is 32
>Graph is /mnt/projects/elephant_shark/analysis/pacbio_ec/jabba/brownie/brownie_output/DBGraph.fasta
>DBG K is 75
>ESSA K is 1
>Max Passes is 2
>Min Seed Size is 20
>Output Directory is output
>Output Mode is short
>Reading the graph... 
>Done.
>Constructing ESSA... 
>atempting to load index output/DBGraph_1_1_1 ... 
>unable to open output/DBGraph_1_1_1
>Command terminated by signal 11

I'm running these commands as root (within a docker container), so I don't think permissions are an issue, and I have plenty of free disk space. In case it proves to be relevant, this is the command I used to generate the de Bruijn graph with brownie:

>#! /bin/bash
>
>/usr/bin/time -v brownie graphCorrection \
>  -p brownie_output/ \
>  -k  75 \
>  ../karect/karect_shotgun.R1.fastq ../karect/karect_shotgun.R2.fastq \
>  2>&1 | tee run.log

Thanks for making awesome open source software and for taking the time to support questions like this, and premature apologies if it proves to be something simple :p

**Comment by gmiclotte** [comment]
Hello,


it appears that essaMEM (the library used by Jabba to construct the suffix array) causes a crash, typically this is because the de Bruijn graph sequence is "too long". This crash can be avoided by increasing the sparseness factor from the default (-e 1).

Commit 62a83bb adds some changes to automatically increase the sparseness factor, so there is no need to manually set it if you update to the latest version of Jabba. If this does not resolve your issue, please let me know.


Kind regards,
Giles Miclotte

**Comment by rcalef** [comment]
That did it, thanks!
